const CAL={
"2026-10-01":["Yaşlılar Haftası","GG KT Anne Çocuk oyun halkası","Ev Sohbetleri Aksiyonu Başlangıcı"],"2026-10-02":["KGT ŞYK Toplantı + Sohbet"],"2026-10-03":["TOM (Açık Cami Günü)","Resmi Tatil"],"2026-10-04":["Bölge KGT 3. SBT (online)","GG KT ŞYK Toplantısı"],"2026-10-05":["Hessen Sonbahar Tatili başlıyor"],"2026-10-07":["İmam Hatipler Toplantısı","GG KT Ev Sohbeti"],"2026-10-09":["KGT ŞYK Toplantı + Sohbet"],"2026-10-10":["Bölge TİES HİE Güney"],"2026-10-16":["Bölge GT GES + Bölge KGT GES","KGT ŞYK Toplantı + Sohbet"],"2026-10-17":["GM 38. AKKTY"],"2026-10-18":["GG KT Sohbet + Hatim + ŞYK Toplantısı","Hessen Sonbahar Tatili bitiyor"],"2026-10-20":["GG KT YEK"],"2026-10-21":["Bölge KT BET"],"2026-10-22":["GG KT Lalezar okumaları","GG KT Anne Çocuk oyun halkası"],"2026-10-23":["KGT ŞYK Toplantı + Sohbet"],"2026-10-24":["KT Güney Emektarlar","Buyrun Ben Müslümanım Projesi"],"2026-10-25":["2. GBYK+GŞYK AT KT GKT"],"2026-10-28":["GG KT YEK","GG KT Ev Sohbeti"],"2026-10-29":["Cumhuriyet Bayramı","GG KT Anne Çocuk oyun halkası"],"2026-10-30":["KGT ŞYK Toplantı + Sohbet"],"2026-10-31":["Bölge AT Hadis-Hutbe Yarışması","KT Güney HUB"],
"2026-11-01":["Bölge 2. GŞBT","GG KT ŞYK Toplantısı","Bölge AT EMMT","GG KT Aile Eğitim Semineri"],"2026-11-03":["GG KT YEK"],"2026-11-04":["İmam Hatipler Toplantısı"],"2026-11-05":["GG KT Anne Çocuk oyun halkası"],"2026-11-06":["KGT ŞYK Toplantı + Sohbet"],"2026-11-08":["Genel Merkez Genel Kurul","Bölge AT + Bölge KT 1. Aile Eğitim Semineri"],"2026-11-10":["GG KT YEK"],"2026-11-11":["GG KT Ev Sohbeti"],"2026-11-12":["GG KT Anne Çocuk oyun halkası"],"2026-11-13":["KGT ŞYK Toplantı + Sohbet"],"2026-11-14":["İrşad Çalıştayı – Bölge KT YES + 5.ŞBT","İrşad Konferansı ve Emektarlar Günü"],"2026-11-15":["Bölge KT YES + 5.ŞBT – GG KT Sohbet + Hatim + ŞYK Toplantısı","AT 3. SBT – KGT KIB Workshop + Topl."],"2026-11-16":["KGT ŞYK Toplantı + Sohbet"],"2026-11-17":["GG KT YEK"],"2026-11-18":["GG KT Lalezar okumaları"],"2026-11-19":["GG KT Anne Çocuk oyun halkası"],"2026-11-20":["KGT ŞYK Toplantı + Sohbet"],"2026-11-21":["GM 23. KT KTKY","GT 4. GİYES"],"2026-11-22":["GG KT 2. Hayır Kahvaltısı","GT 4.ŞBT + GT 4. GİYES – ŞÖBT & Ablalar Buluşması"],"2026-11-24":["GG KT YEK"],"2026-11-25":["GG KT Ev Sohbeti"],"2026-11-26":["KGT ŞYK Toplantı + Sohbet","GG KT Anne Çocuk oyun halkası"],"2026-11-28":["Bölge GİS + Anma Programı","KGT 6.GİYES 5. AEP 4. AL"],"2026-11-29":["2. Üyeler Toplantısı GG","KT Güney 1.Aile Okulu"],
"2026-12-01":["GG KT YEK"],"2026-12-02":["İmam Hatipler Toplantısı"],"2026-12-03":["Dünya Engelliler Günü","GG KT Anne Çocuk oyun halkası"],"2026-12-04":["KGT ŞYK Toplantı + Sohbet"],"2026-12-05":["Bölge AT 4.ŞBT ve 2.BET YES"],"2026-12-06":["KT Güney 2.Aile Okulu","GG Sabah Namazı Programı","GG KT ŞYK Toplantısı","Bölge AT 4.ŞBT ve 2.BET YES"],"2026-12-08":["GG KT YEK"],"2026-12-09":["GG KT Ev Sohbeti"],"2026-12-10":["Üç Ayların Başlangıcı – Regaib Kandili","GG KT Anne Çocuk oyun halkası"],"2026-12-11":["KGT ŞYK Toplantı + Sohbet"],"2026-12-12":["Bölge KGT 4.ŞBT","Bölge GT 3.ÜniYES"],"2026-12-13":["GG Sabah Namazı Programı","Bölge GT 3. ÜniYES","Bölge Umre Semineri","Bölge GT 2.BET"],"2026-12-15":["GG KT YEK"],"2026-12-16":["GG KT Lalezar okumaları"],"2026-12-17":["GG KT Anne Çocuk oyun halkası"],"2026-12-18":["KGT ŞYK Toplantı + Sohbet"],"2026-12-20":["Bölge AT + Bölge KT 2. Aile Eğitim Semineri","GG Sabah Namazı Programı – Abi Kardeş Haftaları Başlıyor"],"2026-12-22":["GG KT YEK"],"2026-12-23":["Hessen Kış Tatili başlıyor","GG KT Ev Sohbeti"],"2026-12-25":["Resmi Tatil","KGT ŞYK Toplantı + Sohbet"],"2026-12-26":["Resmi Tatil","Bölge KGT 3. GES"],"2026-12-27":["GG Sabah Namazı Programı – GG KT Sohbet + Hatim + ŞYK Toplantısı","KT Güney 3.Aile Okulu"],"2026-12-31":["Abi Kardeş Haftaları Bitiyor"]};
let calMonth=9,calYear=2026;
function renderCalendar(){const names=['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'],months=['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'];$('#calTitle').textContent=months[calMonth]+' '+calYear;let first=new Date(calYear,calMonth,1),start=(first.getDay()+6)%7,days=new Date(calYear,calMonth+1,0).getDate();let h=names.map(n=>`<div class="cal-weekday">${n}</div>`).join('');for(let i=0;i<start;i++)h+='<div class="cal-day muted-day"></div>';for(let d=1;d<=days;d++){let key=`${calYear}-${String(calMonth+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,ev=CAL[key]||[];h+=`<button class="cal-day ${ev.length?'has-events':''}" data-day="${key}"><span class="day-number">${d}</span>${ev.slice(0,2).map(x=>`<span class="cal-event">${esc(x)}</span>`).join('')}${ev.length>2?`<span class="more">+${ev.length-2}</span>`:''}</button>`}$('#calendar').innerHTML=h;$$('.cal-day[data-day]').forEach(b=>b.onclick=()=>openDay(b.dataset.day))}
function openDay(key){let ev=CAL[key]||[],d=new Date(key+'T12:00:00');$('#dayTitle').textContent=new Intl.DateTimeFormat('tr-TR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d);$('#dayEvents').innerHTML=ev.map(x=>`<div class="day-event"><span>●</span><p>${esc(x)}</p></div>`).join('');$('#dayModal').classList.remove('hidden')}
$('#prevMonth').onclick=()=>{calMonth--;if(calMonth<0){calMonth=11;calYear--}renderCalendar()};$('#nextMonth').onclick=()=>{calMonth++;if(calMonth>11){calMonth=0;calYear++}renderCalendar()};

const KEY={a:"kg_activities",n:"kg_notices",g:"kg_gallery"};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const get=k=>JSON.parse(localStorage.getItem(k)||"[]"), set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
$("#year").textContent=new Date().getFullYear();

$("#menu").onclick=()=>$("#nav").classList.toggle("open");
$$("nav a").forEach(a=>a.onclick=()=>$("#nav").classList.remove("open"));
$$(".admin-open").forEach(b=>b.onclick=()=>$("#"+b.dataset.modal).classList.remove("hidden"));
$$(".modal").forEach(m=>{m.onclick=e=>{if(e.target===m)m.classList.add("hidden")};m.querySelector(".close").onclick=()=>m.classList.add("hidden")});

const esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const date=s=>s?new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(s+"T12:00:00")):"";

function renderActivities(){
 let a=get(KEY.a).sort((x,y)=>(y.date||"").localeCompare(x.date||"")); $("#activityGrid").innerHTML="";
 $("#activityEmpty").style.display=a.length?"none":"block";
 a.forEach(x=>{let d=document.createElement("article");d.className="card";d.innerHTML=`${x.images?.[0]?`<img class="card-img" src="${x.images[0]}" alt="">`:`<div class="card-img"></div>`}<div class="card-body">${x.date?`<div class="date">${esc(date(x.date))}</div>`:""}<h3>${esc(x.title)}</h3>${x.text?`<p>${esc(x.text)}</p>`:""}<button class="delete">Aktivität löschen</button></div>`;d.querySelector(".delete").onclick=()=>{set(KEY.a,get(KEY.a).filter(y=>y.id!==x.id));renderAll()};$("#activityGrid").append(d)})}
function renderNotices(){
 let n=get(KEY.n).sort((x,y)=>y.id-x.id);$("#noticeList").innerHTML="";$("#noticeEmpty").style.display=n.length?"none":"block";
 n.forEach(x=>{let d=document.createElement("article");d.className="notice";d.innerHTML=`<small>${esc(date(x.date))}</small><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p><button class="delete" style="color:#b9dccc">Duyuruyu sil</button>`;d.querySelector(".delete").onclick=()=>{set(KEY.n,get(KEY.n).filter(y=>y.id!==x.id));renderAll()};$("#noticeList").append(d)})}
function renderGallery(){
 let g=get(KEY.g);$("#gallery").innerHTML="";$("#galleryEmpty").style.display=g.length?"none":"block";
 g.forEach(x=>{let f=document.createElement("figure");f.innerHTML=`<img src="${x.src}" alt="Aktivite fotoğrafı"><button>×</button>`;f.querySelector("button").onclick=()=>{set(KEY.g,get(KEY.g).filter(y=>y.id!==x.id));renderAll()};$("#gallery").append(f)})}

function filesToData(files){return Promise.all([...files].map(f=>new Promise((res,rej)=>{let r=new FileReader;r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})))}

$("#activityForm").onsubmit=async e=>{e.preventDefault();let imgs=await filesToData($("#aImages").files);let item={id:Date.now(),title:$("#aTitle").value.trim(),date:$("#aDate").value,text:$("#aText").value.trim(),images:imgs};let a=get(KEY.a);a.push(item);set(KEY.a,a);let g=get(KEY.g);imgs.forEach(src=>g.push({id:Date.now()+Math.random(),src}));set(KEY.g,g);e.target.reset();e.target.closest(".modal").classList.add("hidden");renderAll()};
$("#noticeForm").onsubmit=e=>{e.preventDefault();let n=get(KEY.n);n.push({id:Date.now(),title:$("#nTitle").value.trim(),text:$("#nText").value.trim(),date:new Date().toISOString().slice(0,10)});set(KEY.n,n);e.target.reset();e.target.closest(".modal").classList.add("hidden");renderAll()};
$("#galleryForm").onsubmit=async e=>{e.preventDefault();let imgs=await filesToData($("#gImages").files),g=get(KEY.g);imgs.forEach(src=>g.push({id:Date.now()+Math.random(),src}));set(KEY.g,g);e.target.reset();e.target.closest(".modal").classList.add("hidden");renderAll()};

function renderAll(){renderActivities();renderNotices();renderGallery()}
renderAll();
renderCalendar();
